server:
  port: 8081
  servlet:
      context-path: /
      jsp:
        registered: false
  error:
    whitelabel: 
      enabled: false
    
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ETIN?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: 1A2Z3E4R5T6Y
  jpa:
    show-sql: true
    generate-ddl: true #true
    hibernate:
       ddl-auto: create #create
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

etin:
    app:
        jwtSecret: jwtEtinSecretKey
        jwtExpiration: 86400